### ISSUE TITLE
New systems roadmap

### ISSUE THREAD

**Issue by Lendersmark** [CkauNui/ckau-book#22]
New Batocera/Retrobat systems to be created/updated:

- [x] cdogs
- [x] wasm4
- [x] amiga4000
- [x] ikemen
- [x] actionmax
- [x] singe2
- [x] pyxel
- [x] multivision
- [x] neogeo64
- [x] pinballfx3
- [x] vemulator
- [x] ps4

Updated systems:

- [x] gamepock
- [x] supervision
- [x] megaduck
- [x] atari800
- [x] VC4000
- [x] oric/oricatmos
- [x] gamemaster
- [x] vsmile
- [x] gamate
- [x] atarist
- [x] amiga500
- [x] gaelco
- [x] naomi
- [x] naomi2
- [x] neogeomvs
- [x] steam
- [x] triforce
- [x] atari800
- [x] atari800 v2 (alternative)
- [x] chihiro
- [x] lightgun v2 (alternative)
- [x] lightgun v3 (alternative)
- [x] snes-msu1
- [x] xboxone
- [x] xboxseriesx
- [x] xboxpass

Others (not officially supported by Batocera/Retrobat, but can be added):

- [x] sc-3000
- [x] p2000t
- [x] makecode
- [x] c16
- [x] xboxone
- [x] win311
- [x] win95
- [x] palm
- [x] iqueplayer
- [x] aleck64
- [x] cbm2
- [x] cps1
- [x] cps2
- [x] cps3
- [x] pockstat
- [x] ngage
- [x] winpopcap
- [x] tiger
- [x] wiiware
- [x ] pegasus
- [x ] nomad

Arcade collections:

- [ ] atari
- [ ] bubble 
- [ ] capcom
- [ ] classic 
- [ ] dataeast
- [x] exboard
- [ ] irem
- [ ] konami
- [ ] konamipc
- [x] locomailto
- [ ] midway
- [ ] namco
- [x] namco11
- [x] namco22
- [x] namcoes3 
- [x] nesicax (taito NESiCAxLive)
- [ ] nintendo
- [x] rawthrills
- [ ] sega
- [x] segaer (sega Europa-R)
- [x] segare (sega RingEdge)
- [x] segarw (sega RingWide)
- [ ] snk
- [ ] taito
- [ ] williams
- [x] zinc

**Comment by Lendersmark** [comment]
Note:
tvgames (Retrobat) = plugnplay (Batocera)
